---
- name: Ensure the /efs directory exists
  file:
    path: /efs
    state: directory

- name: Copy efs id files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: mongodb-build-system-id
      dest: /etc/mongodb-build-system-id
    - src: mongodb-distro-name
      dest: /etc/mongodb-distro-name

- name: Mount efs
  mount:
    state: mounted
    path: "{{ efs_path }}"
    opts: "{{ efs_mount_options }}"
    fstype: "{{ efs_fstype }}"
    src: "{{ efs_src }}"

- name: Make required directories
  file:
    owner: "{{ efs_directory_owner }}"
    state: directory
    mode: 0755
    path: '{{ item }}'
  loop:
    - /efs/{{ build_system_id }}
    - /efs/{{ build_system_id }}/scons-cache
    - /efs/{{ build_system_id }}/info

- name: Copy disto name
  template:
    src: mongodb-distro-name
    dest: /efs/{{ build_system_id }}/info/distro_name

# If we are a patch build, stamp directory with is_patch for future cleanup
- name: Create is_patch file
  file:
    state: touch
    owner: root
    group: root
    mode: 0655
    path: '/efs/{{ build_system_id }}/info/is_patch'
  when:
    - is_patch | default(false)
