---
- become: true
  name: Converge
  hosts: all
  roles:
    - role: ansible-role-efs
      vars:
        efs_directory_owner: root
        efs_src: /tmp/efs
        efs_mount_options: bind
        efs_fstype: none
