---
- gather_facts: false
  name: Setup RHEL6
  hosts: rhel6
  tasks:
    - name: Subscribe container
      redhat_subscription:
        auto_attach: true
        force_register: true
        password: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD') }}"
        username: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME') }}"
    - name: Install sudo
      yum:
        name: sudo
        state: present

- gather_facts: false
  become: true
  name: Create
  hosts: all
  tasks:
    - name: Create temp efs directory
      file:
        path: /tmp/efs
        mode: 0755
        state: directory

    - name: Create temp file in efs directory
      file:
        path: /tmp/efs/test
        mode: 0755
        state: touch
